apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ilijajolevski/jku-cloudnative
    targetRevision: HEAD
    path: gitops
  destination: 
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true